# Generated by Django 4.1.7 on 2024-02-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_alter_message_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='choose_upload_file',
        ),
    ]
