# Generated by Django 4.1.7 on 2024-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0003_rename_file_message_choose_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='choose_upload_file',
            new_name='file',
        ),
    ]
