# Generated by Django 4.1.7 on 2024-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0004_rename_choose_upload_file_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(blank=True, choices=[('Не получил', 'Не получил'), ('В работе', 'В работе'), ('Готово', 'Готово')], default='Не получил', max_length=20),
        ),
    ]
