# Generated by Django 4.1.7 on 2024-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0005_alter_task_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
