# Generated by Django 4.1.7 on 2024-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0006_customuser_about_me_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
