# Generated by Django 4.1.7 on 2024-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0007_alter_customuser_about_me_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='links_to_messengers',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_site',
            field=models.BooleanField(default=True),
        ),
    ]
