# Generated by Django 4.1.7 on 2024-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0009_remove_customuser_links_to_messengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='links_to_messengers',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
