# Generated by Django 4.1.7 on 2024-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0012_alter_customuser_links_to_messengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='links_to_messengers',
            field=models.CharField(default='', max_length=300),
        ),
    ]
