# Generated by Django 4.1.7 on 2024-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0017_alter_customuser_links_to_messengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='links_to_messengers',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
