# Generated by Django 4.1.7 on 2024-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0019_customuser_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_user',
            field=models.CharField(max_length=10),
        ),
    ]
