# Generated by Django 4.1.7 on 2024-04-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0021_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
